### ISSUE TITLE
Sasshoff support

### ISSUE THREAD

**Issue by neilgupta** [mziwisky/puppyhoff.me#12]
Add a sass.puppyhoff.me script to use a sassysolson picture rather than puppyhoff. Picture can be sourced from https://www.flickr.com/photos/ktgeek/albums/72157677589687201/with/32353177516/

Maybe post to #sassysolson too?

**Comment by mziwisky** [comment]
we can definitely get the new subdomain up and running.  i feel the slack channel post would not be in the spirit of puppyhoff.me, which is meant to be a single-purpose tool

**Comment by neilgupta** [comment]
true, +1 on not slacking
