### ISSUE TITLE
"Change picture every X minutes" on OSX prevents puppyhoffing

### ISSUE THREAD

**Issue by mziwisky** [mziwisky/puppyhoff.me#9]
confirmed on OSX 10.11.3
1) in Desktop & Screen Saver prefs, check "Change picture: Every X minutes"
2) try puppyhoffing
3) desktop changes to non-puppyhoff :disappointed:

**Comment by tennety** [comment]
dupe of #4 ?

**Comment by mziwisky** [comment]
ah yes, good catch.  man, it's so hard to keep track of a single-digit number of open issues... closed in favor of #4
